### PR TITLE
[RFC] Add support for Docker image

### PR DESCRIPTION
**Pull request by claudyus**
This PR add the support for docker image build, configuration of the main parameters using ENV, print the pubkey in configuration page to speedup setup.

This is a wip code on Docker integration and I would know if you have any interest in supporting Docker  or not.

### CODE REVIEW

**Comment by Glavin001** [comment]
This is very interesting. I am not personally using Docker for this project, however I think that is a good idea. Maybe other users would also be interested in this as well. Thanks for contributing! Let me know when this WIP is completed.

**Comment by huglester** [comment]
I think others for sure will be interested :) Docker is right tool for this project!

also +1 for using .env file!

**Comment by claudyus** [comment]
I complete the develop of Docker integration. Now you review and merge it, @Glavin001

**Comment by Glavin001** [comment]
Awesome work! Thank for @claudyus :smiley:

**Pull request merged**
