### PR TITLE
Does not checkout the `afterCommit` in the cloned repo

### PR DESCRIPTION
**Pull request by octomike**
Without this addition we are only seeing master checked out.
Are we doing it wrong or was that bug?

### CODE REVIEW

**Comment by Glavin001** [comment]
It uses the [after commit](https://github.com/Glavin001/GitLab-Pages/blob/master/routes/webhooks.js#L19) from the webhook payload from GitLab,  and then checks out that commit at https://github.com/Glavin001/GitLab-Pages/blob/master/routes/webhooks.js#L57
It should only apply when the test passes for if the `deployBranch` is the branch that has been pushed, see https://github.com/Glavin001/GitLab-Pages/blob/master/routes/webhooks.js#L22-L27 

### tl;dr

So really it does not even checkout the branch, it checks out the commit that was most recently pushed, and only if that commit lies within that `deployBranch`.

---

I'll take a look later this week when I get a chance and see if it's a true bug. Could you detail some steps I could use to reproduce? For instance, enable repo for GitLab Pages, set `deployBranch` to `gl-pages`, push branch `master`, notice that it does still change. This would indicate there's a bug in the check at https://github.com/Glavin001/GitLab-Pages/blob/master/routes/webhooks.js#L22-L27

**Comment by octomike** [comment]
Thanks for the explanation!
But unfortunately it still does not work here.
Is [repo.getCommit()](https://github.com/Glavin001/GitLab-Pages/blob/master/routes/webhooks.js#L57) implicitly checking out that commit in the tmp folder? Because that's not happening in our installation.

**Comment by Glavin001** [comment]
Yes, it should be checking that commit out in the clone, which is in the tmp directory.

Could you:
- confirm that https://github.com/Glavin001/GitLab-Pages/blob/master/routes/webhooks.js#L22-L27 is working/not working (use proper deploy branch, use master, etc)
- see if it is properly checking out the commit at https://github.com/Glavin001/GitLab-Pages/blob/master/routes/webhooks.js#L57 (sounds like it is not form your comment above) and then see what `afterCommit` is at that time (valid?). It may be an issue with NodeGit itself.

**Comment by octomike** [comment]
- ref equals deployRef ("refs/heads/gl-pages") in https://github.com/Glavin001/GitLab-Pages/blob/master/routes/webhooks.js#L22-L27
- afterCommit is containing the correct sha sum in https://github.com/Glavin001/GitLab-Pages/blob/master/routes/webhooks.js#L57
- but still .tmp/ contains the repo with master checked out and hence jekyll will "build" master

Manually checking it out in .tmp/ works fine. How do I debug that repo.getCommit(afterCommit)[https://github.com/Glavin001/GitLab-Pages/blob/master/routes/webhooks.js#L57] call further?

**Comment by Glavin001** [comment]
It looks like a NodeGit bug. I've found others, too. See https://github.com/nodegit/nodegit/issues/341#issuecomment-71384969

They recommend that you discuss with them on their [Gitter channel](https://gitter.im/nodegit/nodegit). Let me know if you're able to resolve this and we can fix this for everyone. Thanks!

**Comment by octomike** [comment]
As suspected.

_Hi @octomike! getCommit(sha) simply returns information about a commit in the repo, it doesn’t affect he working directory._ ( https://gitter.im/nodegit/nodegit )

**Comment by Glavin001** [comment]
Well, that explains a lot.. haha. Thanks for looking into that!

**Comment by Glavin001** [comment]
Use `Checkout.tree`, see http://www.nodegit.org/#Checkout/function/tree

Thanks to @orderedlist

**Comment by octomike** [comment]
Meh, the updated pull request doesn't work. Ignore that please :)

**Comment by Glavin001** [comment]
Does it not checkout the commit still? Bummer. If it's not that then what NodeGit API call?

**Comment by octomike** [comment]
Tested, works fine. Once they actually implemented what's in the API, you can use the line in the comment. :smile_cat:

**Comment by Glavin001** [comment]
So `Checkout.tree` is not implemented in NodeGit API yet? I thought that's what was recommended to use.. :confused:

**Comment by octomike** [comment]
Yes, I just asked in their gitter channel.

**Comment by Glavin001** [comment]
Wow, it's unfortunate that NodeGit is so unusable in it's current state. I may even investigate using [`exec` or `spawn`](http://nodejs.org/api/child_process.html) as a more viable solution for the time being.

**Comment by acao** [comment]
Probably because js-git has become so popular! This is a node wrapper for it.

https://www.npmjs.com/package/git-node

**Comment by Glavin001** [comment]
Great! Then it looks like switching to use jsgit is a good idea.

**Comment by Glavin001** [comment]
Closing this and moving to #11. I am open to reviewing Pull Requests for #11. Thanks!

**Comment by Glavin001** [comment]
I think git checkout tree is implemented now! 
See https://github.com/nodegit/nodegit/pull/402 and http://www.nodegit.org/api/checkout/#tree

**Comment by Glavin001** [comment]
I recommend updating GitLab Pages and this should now work. Let me know if there are any other problems. Thanks!

**Pull request closed without merging**
